version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: todo_db
    environment:
      POSTGRES_USER: sc
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: praydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  

volumes:
  pgdata: